#Updated Service Config
#Thu Mar 05 18:35:02 IST 2026
box.migration.folder.id=369364083732
db.password=
box.config.path=C\:/temp/apps/properties/Box/BoxEnv1.json
box.error.queue.folder.id=359955901523
ntfs.target.dir=c\:\\temp
db.username=root
ntfs.archive.dir=C\:/move/archive
load.dir=C\:/temp/NTFS
extractor.dir=C\:/temp/NTFS
poll.interval.ms=5000
box.archive.folder.id=358518450039
load.error.queue.dir=C\:/box/error
ntfs.queue.dir=C\:/move/queue
db.driverClassName=com.mysql.jdbc.Driver
box.meta.data.folder.id=359155290193
box.app.user.id=47676299876
db.url=jdbc\:mysql\://localhost\:3306/docxfer
ntfs.source.dir=C\:/temp/NTFS
ntfs.meta.data.dir=C\:/temp/Metadata
